In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
np.__version__

'2.3.1'

In [5]:
list1 = [1,2,3]

In [6]:
arr1 = np.array(list1)

In [7]:
arr1

array([1, 2, 3])

In [8]:
arr1.shape

(3,)

In [10]:
arr1.ndim

1

In [12]:
list2= [[1,2,3],
        [6,7,8],
        [3,4,5]]

In [13]:
arr2 = np.array(list2)

In [14]:
arr2.shape

(3, 3)

In [16]:
arr2.ndim

2

In [23]:
np.zeros((4,4),dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
arr3 = np.ones((2,3,3), dtype="int8")

In [27]:
arr3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [28]:
arr3.shape

(2, 3, 3)

In [29]:
arr3.ndim

3

In [31]:
np.full((3,4), fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [34]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [37]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [38]:
np.random.randint(0,10,size=(2,2))

array([[6, 3],
       [7, 6]], dtype=int32)