In [29]:
!pip install numpy

In [30]:
import numpy as np

In [31]:
np.__version__

'2.3.1'

In [32]:
list1 = [1,2,3]

In [33]:
arr1 = np.array(list1)

In [34]:
arr1

array([1, 2, 3])

In [35]:
arr1.shape

(3,)

In [36]:
arr1.ndim

1

In [37]:
list2= [[1,2,3],
        [6,7,8],
        [3,4,5]]

In [38]:
arr2 = np.array(list2)

In [39]:
arr2.shape

(3, 3)

In [40]:
arr2.ndim

2

In [41]:
np.zeros((4,4),dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
arr3 = np.ones((2,3,3), dtype="int8")

In [43]:
arr3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [44]:
arr3.shape

(2, 3, 3)

In [45]:
arr3.ndim

3

In [46]:
np.full((3,4), fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [47]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [48]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [49]:
np.random.randint(0,10,size=(2,2))

array([[9, 4],
       [1, 9]], dtype=int32)

In [50]:
np.ones((2,2,1,3), dtype="int8")

array([[[[1, 1, 1]],

        [[1, 1, 1]]],


       [[[1, 1, 1]],

        [[1, 1, 1]]]], dtype=int8)

In [51]:
a = np.array([1,2,3,4,5])

In [52]:
a[-3]

np.int64(3)

In [55]:
a[::-1]

array([5, 4, 3, 2, 1])

In [57]:
#2d
b = np.random.randint(0,10,(3,3))
b

array([[1, 3, 4],
       [0, 0, 5],
       [1, 5, 5]], dtype=int32)

In [58]:
b[1,1]

np.int32(0)

In [59]:
b[2,2]

np.int32(5)

In [61]:
b[-1,0]

np.int32(1)

In [62]:
b[1:4,:2]

array([[0, 0],
       [1, 5]], dtype=int32)

In [64]:
c = np.random.randint(0,25,(3,3,2))
c

array([[[ 3, 19],
        [ 9, 21],
        [11,  7]],

       [[ 6,  0],
        [ 6, 17],
        [11, 21]],

       [[ 2, 18],
        [17, 15],
        [ 6, 14]]], dtype=int32)

In [66]:
c[1,1,1]

np.int32(17)

In [67]:
c[1][1][1]

np.int32(17)

In [68]:
c[:,2,:]

array([[11,  7],
       [11, 21],
       [ 6, 14]], dtype=int32)

In [75]:
dataset = np.random.randint(0,100,(16000,25))
dataset

array([[22, 68, 17, ..., 70, 45, 16],
       [38,  3, 79, ..., 86, 27, 39],
       [63, 59, 95, ..., 14, 79, 58],
       ...,
       [81, 78, 95, ..., 60, 62,  9],
       [72, 13, 32, ..., 95,  1, 92],
       [12, 56, 94, ..., 28, 61, 83]], shape=(16000, 25), dtype=int32)

In [76]:
dataset[:,0]

array([22, 38, 63, ..., 81, 72, 12], shape=(16000,), dtype=int32)

In [79]:
a = np.random.randint(1,10,(5,5))
a

array([[9, 9, 7, 3, 8],
       [8, 2, 1, 6, 9],
       [7, 4, 1, 4, 7],
       [9, 6, 1, 6, 3],
       [9, 8, 6, 9, 3]], dtype=int32)

In [80]:
mask = a > 5

In [81]:
mask

array([[ True,  True,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True, False, False, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True, False]])

In [86]:
a[ mask]

array([[9, 9, 7, 3, 8],
       [9, 6, 1, 6, 3],
       [9, 8, 6, 9, 3]], dtype=int32)

In [83]:
mask = [True, False, False, True, True]

In [88]:
a[:,mask]

array([[9, 3, 8],
       [8, 6, 9],
       [7, 4, 7],
       [9, 6, 3],
       [9, 9, 3]], dtype=int32)