In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,50,(5,2,3))
a

array([[[13, 29, 46],
        [38, 21, 38]],

       [[33, 30, 23],
        [27, 33, 12]],

       [[32, 44, 17],
        [39, 10, 19]],

       [[39, 46, 35],
        [24, 28, 46]],

       [[14, 36, 48],
        [13, 32, 22]]], dtype=int32)

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int32')

In [6]:
a.size

30

In [7]:
a.T

array([[[13, 33, 32, 39, 14],
        [38, 27, 39, 24, 13]],

       [[29, 30, 44, 46, 36],
        [21, 33, 10, 28, 32]],

       [[46, 23, 17, 35, 48],
        [38, 12, 19, 46, 22]]], dtype=int32)

In [8]:
a.reshape(3,5,2)

array([[[13, 29],
        [46, 38],
        [21, 38],
        [33, 30],
        [23, 27]],

       [[33, 12],
        [32, 44],
        [17, 39],
        [10, 19],
        [39, 46]],

       [[35, 24],
        [28, 46],
        [14, 36],
        [48, 13],
        [32, 22]]], dtype=int32)

In [9]:
a.reshape(3,-1,2)

array([[[13, 29],
        [46, 38],
        [21, 38],
        [33, 30],
        [23, 27]],

       [[33, 12],
        [32, 44],
        [17, 39],
        [10, 19],
        [39, 46]],

       [[35, 24],
        [28, 46],
        [14, 36],
        [48, 13],
        [32, 22]]], dtype=int32)

In [10]:
a.ravel()

array([13, 29, 46, 38, 21, 38, 33, 30, 23, 27, 33, 12, 32, 44, 17, 39, 10,
       19, 39, 46, 35, 24, 28, 46, 14, 36, 48, 13, 32, 22], dtype=int32)

In [11]:
a.flatten()

array([13, 29, 46, 38, 21, 38, 33, 30, 23, 27, 33, 12, 32, 44, 17, 39, 10,
       19, 39, 46, 35, 24, 28, 46, 14, 36, 48, 13, 32, 22], dtype=int32)

In [12]:
b = np.random.randint(1,10,(2,3))
c = np.random.randint(1,10,(2,4))
b, c

(array([[5, 6, 6],
        [6, 6, 3]], dtype=int32),
 array([[2, 2, 1, 9],
        [2, 4, 9, 1]], dtype=int32))

In [13]:
d = np.concatenate([b,c], axis=1)
d

array([[5, 6, 6, 2, 2, 1, 9],
       [6, 6, 3, 2, 4, 9, 1]], dtype=int32)

In [14]:
np.hstack((b,c))

array([[5, 6, 6, 2, 2, 1, 9],
       [6, 6, 3, 2, 4, 9, 1]], dtype=int32)

In [15]:
np.split(d,2,axis=0)

[array([[5, 6, 6, 2, 2, 1, 9]], dtype=int32),
 array([[6, 6, 3, 2, 4, 9, 1]], dtype=int32)]

In [16]:
z = np.random.randint(1,10,(4,6))
z

array([[7, 2, 4, 9, 4, 4],
       [1, 7, 8, 2, 5, 7],
       [6, 7, 9, 2, 9, 8],
       [2, 7, 1, 8, 6, 8]], dtype=int32)

In [18]:
z.sum(axis = 0)

array([16, 23, 22, 21, 24, 27])

In [20]:
z.prod(axis = 0)

array([  84,  686,  288,  288, 1080, 1792])

In [21]:
z.prod(axis = 1)

array([ 8064,  3920, 54432,  5376])

In [23]:
z.cumsum(axis = 0)

array([[ 7,  2,  4,  9,  4,  4],
       [ 8,  9, 12, 11,  9, 11],
       [14, 16, 21, 13, 18, 19],
       [16, 23, 22, 21, 24, 27]])

In [24]:
z.cumsum(axis = 0)

array([[ 7,  2,  4,  9,  4,  4],
       [ 8,  9, 12, 11,  9, 11],
       [14, 16, 21, 13, 18, 19],
       [16, 23, 22, 21, 24, 27]])

In [25]:
z.min()

np.int32(1)

In [26]:
z.min(axis=1)

array([2, 1, 2, 1], dtype=int32)

In [27]:
z.max(axis=0)

array([7, 7, 9, 9, 9, 8], dtype=int32)

In [29]:
z.argmax(axis=1)

array([3, 2, 2, 3])

In [30]:
z.argmin(axis=1)

array([1, 0, 3, 2])

In [31]:
z

array([[7, 2, 4, 9, 4, 4],
       [1, 7, 8, 2, 5, 7],
       [6, 7, 9, 2, 9, 8],
       [2, 7, 1, 8, 6, 8]], dtype=int32)

In [32]:
z.clip(5,10)

array([[7, 5, 5, 9, 5, 5],
       [5, 7, 8, 5, 5, 7],
       [6, 7, 9, 5, 9, 8],
       [5, 7, 5, 8, 6, 8]], dtype=int32)