In [1]:
import numpy as np

In [3]:
a = np.random.randint(10,50,(5,2,3))
a

array([[[25, 30, 19],
        [23, 24, 14]],

       [[19, 11, 10],
        [14, 32, 28]],

       [[16, 38, 41],
        [36, 45, 44]],

       [[11, 39, 17],
        [21, 11, 42]],

       [[38, 19, 41],
        [11, 44, 13]]], dtype=int32)

In [4]:
a.shape

(5, 2, 3)

In [5]:
a.ndim

3

In [6]:
a.dtype

dtype('int32')

In [7]:
a.size

30

In [8]:
a.T

array([[[25, 19, 16, 11, 38],
        [23, 14, 36, 21, 11]],

       [[30, 11, 38, 39, 19],
        [24, 32, 45, 11, 44]],

       [[19, 10, 41, 17, 41],
        [14, 28, 44, 42, 13]]], dtype=int32)

In [9]:
a.reshape(3,5,2)

array([[[25, 30],
        [19, 23],
        [24, 14],
        [19, 11],
        [10, 14]],

       [[32, 28],
        [16, 38],
        [41, 36],
        [45, 44],
        [11, 39]],

       [[17, 21],
        [11, 42],
        [38, 19],
        [41, 11],
        [44, 13]]], dtype=int32)

In [10]:
a.reshape(3,-1,2)

array([[[25, 30],
        [19, 23],
        [24, 14],
        [19, 11],
        [10, 14]],

       [[32, 28],
        [16, 38],
        [41, 36],
        [45, 44],
        [11, 39]],

       [[17, 21],
        [11, 42],
        [38, 19],
        [41, 11],
        [44, 13]]], dtype=int32)

In [11]:
a.ravel()

array([25, 30, 19, 23, 24, 14, 19, 11, 10, 14, 32, 28, 16, 38, 41, 36, 45,
       44, 11, 39, 17, 21, 11, 42, 38, 19, 41, 11, 44, 13], dtype=int32)

In [12]:
a.flatten()

array([25, 30, 19, 23, 24, 14, 19, 11, 10, 14, 32, 28, 16, 38, 41, 36, 45,
       44, 11, 39, 17, 21, 11, 42, 38, 19, 41, 11, 44, 13], dtype=int32)

In [16]:
b = np.random.randint(1,10,(2,3))
c = np.random.randint(1,10,(2,4))
b, c

(array([[8, 1, 8],
        [1, 2, 5]], dtype=int32),
 array([[3, 9, 9, 4],
        [1, 8, 6, 7]], dtype=int32))

In [23]:
d = np.concatenate([b,c], axis=1)
d

array([[8, 1, 8, 3, 9, 9, 4],
       [1, 2, 5, 1, 8, 6, 7]], dtype=int32)

In [24]:
np.hstack((b,c))

array([[8, 1, 8, 3, 9, 9, 4],
       [1, 2, 5, 1, 8, 6, 7]], dtype=int32)

In [31]:
np.split(d,2,axis=0)

[array([[8, 1, 8, 3, 9, 9, 4]], dtype=int32),
 array([[1, 2, 5, 1, 8, 6, 7]], dtype=int32)]