In [1]:
import numpy as np

In [2]:
a = np.array([[4,5,6],
             [5,7,9]])
b = np.array([[3,2,1],
             [9,8,1]])
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [9, 8, 1]]))

In [3]:
np.add(a,b)

array([[ 7,  7,  7],
       [14, 15, 10]])

In [4]:
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -1,  8]])

In [5]:
np.multiply(a,b)

array([[12, 10,  6],
       [45, 56,  9]])

In [6]:
np.square(a)

array([[16, 25, 36],
       [25, 49, 81]])

In [7]:
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 81]])

In [8]:
quo,rem = np.divmod(a,b)

In [9]:
quo

array([[1, 2, 6],
       [0, 0, 9]])

In [10]:
rem

array([[1, 1, 0],
       [5, 7, 0]])

In [11]:
c = np.sqrt(a)

In [12]:
c

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

In [13]:
np.ceil(c)

array([[2., 3., 3.],
       [3., 3., 3.]])

In [14]:
np.floor(c)

array([[2., 2., 2.],
       [2., 2., 3.]])

In [15]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.41211849]])

In [16]:
d = 1/np.tan(b)
d

array([[-7.01525255, -0.45765755,  0.64209262],
       [-2.21084541, -0.14706506,  0.64209262]])

In [17]:
np.round(d, decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

In [18]:
np.around(d,decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

In [19]:
np.fix(d)

array([[-7., -0.,  0.],
       [-2., -0.,  0.]])

In [25]:
a = np.array([[1,2,3],
             [4,5,6]])
b=np.random.randint(0,10,(2,3,3))
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[3, 1, 8],
         [7, 1, 9],
         [0, 7, 9]],
 
        [[3, 7, 2],
         [7, 0, 9],
         [9, 6, 3]]], dtype=int32))

In [26]:
np.dot(a,b)

array([[[ 17,  24,  53],
        [ 44,  25,  29]],

       [[ 47,  51, 131],
        [101,  64,  71]]])

In [27]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
np.trace(b)

array([10,  1, 17])

In [31]:
np.linalg.det(b)

array([167., 342.])

In [32]:
np.linalg.inv(b)

array([[[-0.32335329,  0.28143713,  0.00598802],
        [-0.37724551,  0.16167665,  0.17365269],
        [ 0.29341317, -0.1257485 , -0.0239521 ]],

       [[-0.15789474, -0.02631579,  0.18421053],
        [ 0.1754386 , -0.02631579, -0.0380117 ],
        [ 0.12280702,  0.13157895, -0.14327485]]])

In [33]:
np.dot(b, np.linalg.inv(b)).round()

array([[[[ 1.,  0.,  0.],
         [ 1.,  1., -1.]],

        [[ 0.,  1.,  0.],
         [ 0.,  1., -0.]],

        [[ 0., -0.,  1.],
         [ 2.,  1., -2.]]],


       [[[-3.,  2.,  1.],
         [ 1.,  0., -0.]],

        [[ 0.,  1., -0.],
         [ 0.,  1.,  0.]],

        [[-4.,  3.,  1.],
         [ 0.,  0.,  1.]]]])

In [41]:
a=np.array([[1,2],[3,5]])
b= np.array([1,2])

In [42]:
x = np.linalg.solve(a,b)
x

array([-1.,  1.])

In [43]:
np.dot(a,x)

array([1., 2.])