In [1]:
import numpy as np

In [15]:
a = np.array([[4,5,6],
             [5,7,9]])
b = np.array([[3,2,1],
             [9,8,1]])
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [9, 8, 1]]))

In [16]:
np.add(a,b)

array([[ 7,  7,  7],
       [14, 15, 10]])

In [17]:
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -1,  8]])

In [18]:
np.multiply(a,b)

array([[12, 10,  6],
       [45, 56,  9]])

In [19]:
np.square(a)

array([[16, 25, 36],
       [25, 49, 81]])

In [20]:
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 81]])

In [23]:
quo,rem = np.divmod(a,b)

In [24]:
quo

array([[1, 2, 6],
       [0, 0, 9]])

In [25]:
rem

array([[1, 1, 0],
       [5, 7, 0]])

In [28]:
c = np.sqrt(a)

In [29]:
c

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

In [30]:
np.ceil(c)

array([[2., 3., 3.],
       [3., 3., 3.]])

In [31]:
np.floor(c)

array([[2., 2., 2.],
       [2., 2., 3.]])

In [32]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.41211849]])

In [41]:
d = 1/np.tan(b)
d

array([[-7.01525255, -0.45765755,  0.64209262],
       [-2.21084541, -0.14706506,  0.64209262]])

In [38]:
np.round(d, decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

In [39]:
np.around(d,decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

In [40]:
np.fix(d)

array([[-7., -0.,  0.],
       [-2., -0.,  0.]])